// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 SAP SE
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package monitors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetMonitorsMonitorIDParams creates a new GetMonitorsMonitorIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMonitorsMonitorIDParams() *GetMonitorsMonitorIDParams {
	return &GetMonitorsMonitorIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMonitorsMonitorIDParamsWithTimeout creates a new GetMonitorsMonitorIDParams object
// with the ability to set a timeout on a request.
func NewGetMonitorsMonitorIDParamsWithTimeout(timeout time.Duration) *GetMonitorsMonitorIDParams {
	return &GetMonitorsMonitorIDParams{
		timeout: timeout,
	}
}

// NewGetMonitorsMonitorIDParamsWithContext creates a new GetMonitorsMonitorIDParams object
// with the ability to set a context for a request.
func NewGetMonitorsMonitorIDParamsWithContext(ctx context.Context) *GetMonitorsMonitorIDParams {
	return &GetMonitorsMonitorIDParams{
		Context: ctx,
	}
}

// NewGetMonitorsMonitorIDParamsWithHTTPClient creates a new GetMonitorsMonitorIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMonitorsMonitorIDParamsWithHTTPClient(client *http.Client) *GetMonitorsMonitorIDParams {
	return &GetMonitorsMonitorIDParams{
		HTTPClient: client,
	}
}

/* GetMonitorsMonitorIDParams contains all the parameters to send to the API endpoint
   for the get monitors monitor ID operation.

   Typically these are written to a http.Request.
*/
type GetMonitorsMonitorIDParams struct {

	/* MonitorID.

	   The UUID of the monitor

	   Format: uuid
	*/
	MonitorID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get monitors monitor ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMonitorsMonitorIDParams) WithDefaults() *GetMonitorsMonitorIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get monitors monitor ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMonitorsMonitorIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get monitors monitor ID params
func (o *GetMonitorsMonitorIDParams) WithTimeout(timeout time.Duration) *GetMonitorsMonitorIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get monitors monitor ID params
func (o *GetMonitorsMonitorIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get monitors monitor ID params
func (o *GetMonitorsMonitorIDParams) WithContext(ctx context.Context) *GetMonitorsMonitorIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get monitors monitor ID params
func (o *GetMonitorsMonitorIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get monitors monitor ID params
func (o *GetMonitorsMonitorIDParams) WithHTTPClient(client *http.Client) *GetMonitorsMonitorIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get monitors monitor ID params
func (o *GetMonitorsMonitorIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMonitorID adds the monitorID to the get monitors monitor ID params
func (o *GetMonitorsMonitorIDParams) WithMonitorID(monitorID strfmt.UUID) *GetMonitorsMonitorIDParams {
	o.SetMonitorID(monitorID)
	return o
}

// SetMonitorID adds the monitorId to the get monitors monitor ID params
func (o *GetMonitorsMonitorIDParams) SetMonitorID(monitorID strfmt.UUID) {
	o.MonitorID = monitorID
}

// WriteToRequest writes these params to a swagger request
func (o *GetMonitorsMonitorIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param monitor_id
	if err := r.SetPathParam("monitor_id", o.MonitorID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
