services:
  mariadb:
    image: mariadb:11.4
    container_name: andromeda-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: andromeda_db
      MYSQL_USER: andromeda
      MYSQL_PASSWORD: andromeda
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
      interval: 10s

  nats:
    image: nats:2.10
    container_name: andromeda-nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["--http_port", "8222"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      timeout: 5s
      retries: 5
      interval: 10s

volumes:
  mariadb_data: