// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 SAP SE
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutDomainsDomainIDParams creates a new PutDomainsDomainIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutDomainsDomainIDParams() *PutDomainsDomainIDParams {
	return &PutDomainsDomainIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutDomainsDomainIDParamsWithTimeout creates a new PutDomainsDomainIDParams object
// with the ability to set a timeout on a request.
func NewPutDomainsDomainIDParamsWithTimeout(timeout time.Duration) *PutDomainsDomainIDParams {
	return &PutDomainsDomainIDParams{
		timeout: timeout,
	}
}

// NewPutDomainsDomainIDParamsWithContext creates a new PutDomainsDomainIDParams object
// with the ability to set a context for a request.
func NewPutDomainsDomainIDParamsWithContext(ctx context.Context) *PutDomainsDomainIDParams {
	return &PutDomainsDomainIDParams{
		Context: ctx,
	}
}

// NewPutDomainsDomainIDParamsWithHTTPClient creates a new PutDomainsDomainIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutDomainsDomainIDParamsWithHTTPClient(client *http.Client) *PutDomainsDomainIDParams {
	return &PutDomainsDomainIDParams{
		HTTPClient: client,
	}
}

/* PutDomainsDomainIDParams contains all the parameters to send to the API endpoint
   for the put domains domain ID operation.

   Typically these are written to a http.Request.
*/
type PutDomainsDomainIDParams struct {

	// Domain.
	Domain PutDomainsDomainIDBody

	/* DomainID.

	   The UUID of the domain

	   Format: uuid
	*/
	DomainID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put domains domain ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutDomainsDomainIDParams) WithDefaults() *PutDomainsDomainIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put domains domain ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutDomainsDomainIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put domains domain ID params
func (o *PutDomainsDomainIDParams) WithTimeout(timeout time.Duration) *PutDomainsDomainIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put domains domain ID params
func (o *PutDomainsDomainIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put domains domain ID params
func (o *PutDomainsDomainIDParams) WithContext(ctx context.Context) *PutDomainsDomainIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put domains domain ID params
func (o *PutDomainsDomainIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put domains domain ID params
func (o *PutDomainsDomainIDParams) WithHTTPClient(client *http.Client) *PutDomainsDomainIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put domains domain ID params
func (o *PutDomainsDomainIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDomain adds the domain to the put domains domain ID params
func (o *PutDomainsDomainIDParams) WithDomain(domain PutDomainsDomainIDBody) *PutDomainsDomainIDParams {
	o.SetDomain(domain)
	return o
}

// SetDomain adds the domain to the put domains domain ID params
func (o *PutDomainsDomainIDParams) SetDomain(domain PutDomainsDomainIDBody) {
	o.Domain = domain
}

// WithDomainID adds the domainID to the put domains domain ID params
func (o *PutDomainsDomainIDParams) WithDomainID(domainID strfmt.UUID) *PutDomainsDomainIDParams {
	o.SetDomainID(domainID)
	return o
}

// SetDomainID adds the domainId to the put domains domain ID params
func (o *PutDomainsDomainIDParams) SetDomainID(domainID strfmt.UUID) {
	o.DomainID = domainID
}

// WriteToRequest writes these params to a swagger request
func (o *PutDomainsDomainIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Domain); err != nil {
		return err
	}

	// path param domain_id
	if err := r.SetPathParam("domain_id", o.DomainID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
