// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 SAP SE
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package members

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sapcc/andromeda/models"
)

// DeletePoolsPoolIDMembersMemberIDReader is a Reader for the DeletePoolsPoolIDMembersMemberID structure.
type DeletePoolsPoolIDMembersMemberIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePoolsPoolIDMembersMemberIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeletePoolsPoolIDMembersMemberIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeletePoolsPoolIDMembersMemberIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDeletePoolsPoolIDMembersMemberIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeletePoolsPoolIDMembersMemberIDNoContent creates a DeletePoolsPoolIDMembersMemberIDNoContent with default headers values
func NewDeletePoolsPoolIDMembersMemberIDNoContent() *DeletePoolsPoolIDMembersMemberIDNoContent {
	return &DeletePoolsPoolIDMembersMemberIDNoContent{}
}

/*
DeletePoolsPoolIDMembersMemberIDNoContent describes a response with status code 204, with default header values.

Resource successfully deleted.
*/
type DeletePoolsPoolIDMembersMemberIDNoContent struct {
}

// IsSuccess returns true when this delete pools pool Id members member Id no content response has a 2xx status code
func (o *DeletePoolsPoolIDMembersMemberIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete pools pool Id members member Id no content response has a 3xx status code
func (o *DeletePoolsPoolIDMembersMemberIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete pools pool Id members member Id no content response has a 4xx status code
func (o *DeletePoolsPoolIDMembersMemberIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete pools pool Id members member Id no content response has a 5xx status code
func (o *DeletePoolsPoolIDMembersMemberIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete pools pool Id members member Id no content response a status code equal to that given
func (o *DeletePoolsPoolIDMembersMemberIDNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *DeletePoolsPoolIDMembersMemberIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /pools/{pool_id}/members/{member_id}][%d] deletePoolsPoolIdMembersMemberIdNoContent ", 204)
}

func (o *DeletePoolsPoolIDMembersMemberIDNoContent) String() string {
	return fmt.Sprintf("[DELETE /pools/{pool_id}/members/{member_id}][%d] deletePoolsPoolIdMembersMemberIdNoContent ", 204)
}

func (o *DeletePoolsPoolIDMembersMemberIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeletePoolsPoolIDMembersMemberIDNotFound creates a DeletePoolsPoolIDMembersMemberIDNotFound with default headers values
func NewDeletePoolsPoolIDMembersMemberIDNotFound() *DeletePoolsPoolIDMembersMemberIDNotFound {
	return &DeletePoolsPoolIDMembersMemberIDNotFound{}
}

/*
DeletePoolsPoolIDMembersMemberIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeletePoolsPoolIDMembersMemberIDNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete pools pool Id members member Id not found response has a 2xx status code
func (o *DeletePoolsPoolIDMembersMemberIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete pools pool Id members member Id not found response has a 3xx status code
func (o *DeletePoolsPoolIDMembersMemberIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete pools pool Id members member Id not found response has a 4xx status code
func (o *DeletePoolsPoolIDMembersMemberIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete pools pool Id members member Id not found response has a 5xx status code
func (o *DeletePoolsPoolIDMembersMemberIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete pools pool Id members member Id not found response a status code equal to that given
func (o *DeletePoolsPoolIDMembersMemberIDNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *DeletePoolsPoolIDMembersMemberIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /pools/{pool_id}/members/{member_id}][%d] deletePoolsPoolIdMembersMemberIdNotFound  %+v", 404, o.Payload)
}

func (o *DeletePoolsPoolIDMembersMemberIDNotFound) String() string {
	return fmt.Sprintf("[DELETE /pools/{pool_id}/members/{member_id}][%d] deletePoolsPoolIdMembersMemberIdNotFound  %+v", 404, o.Payload)
}

func (o *DeletePoolsPoolIDMembersMemberIDNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeletePoolsPoolIDMembersMemberIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeletePoolsPoolIDMembersMemberIDDefault creates a DeletePoolsPoolIDMembersMemberIDDefault with default headers values
func NewDeletePoolsPoolIDMembersMemberIDDefault(code int) *DeletePoolsPoolIDMembersMemberIDDefault {
	return &DeletePoolsPoolIDMembersMemberIDDefault{
		_statusCode: code,
	}
}

/*
DeletePoolsPoolIDMembersMemberIDDefault describes a response with status code -1, with default header values.

Unexpected Error
*/
type DeletePoolsPoolIDMembersMemberIDDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the delete pools pool ID members member ID default response
func (o *DeletePoolsPoolIDMembersMemberIDDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this delete pools pool ID members member ID default response has a 2xx status code
func (o *DeletePoolsPoolIDMembersMemberIDDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete pools pool ID members member ID default response has a 3xx status code
func (o *DeletePoolsPoolIDMembersMemberIDDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete pools pool ID members member ID default response has a 4xx status code
func (o *DeletePoolsPoolIDMembersMemberIDDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete pools pool ID members member ID default response has a 5xx status code
func (o *DeletePoolsPoolIDMembersMemberIDDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete pools pool ID members member ID default response a status code equal to that given
func (o *DeletePoolsPoolIDMembersMemberIDDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *DeletePoolsPoolIDMembersMemberIDDefault) Error() string {
	return fmt.Sprintf("[DELETE /pools/{pool_id}/members/{member_id}][%d] DeletePoolsPoolIDMembersMemberID default  %+v", o._statusCode, o.Payload)
}

func (o *DeletePoolsPoolIDMembersMemberIDDefault) String() string {
	return fmt.Sprintf("[DELETE /pools/{pool_id}/members/{member_id}][%d] DeletePoolsPoolIDMembersMemberID default  %+v", o._statusCode, o.Payload)
}

func (o *DeletePoolsPoolIDMembersMemberIDDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeletePoolsPoolIDMembersMemberIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
