// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 SAP SE
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package members

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutPoolsPoolIDMembersMemberIDParams creates a new PutPoolsPoolIDMembersMemberIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutPoolsPoolIDMembersMemberIDParams() *PutPoolsPoolIDMembersMemberIDParams {
	return &PutPoolsPoolIDMembersMemberIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutPoolsPoolIDMembersMemberIDParamsWithTimeout creates a new PutPoolsPoolIDMembersMemberIDParams object
// with the ability to set a timeout on a request.
func NewPutPoolsPoolIDMembersMemberIDParamsWithTimeout(timeout time.Duration) *PutPoolsPoolIDMembersMemberIDParams {
	return &PutPoolsPoolIDMembersMemberIDParams{
		timeout: timeout,
	}
}

// NewPutPoolsPoolIDMembersMemberIDParamsWithContext creates a new PutPoolsPoolIDMembersMemberIDParams object
// with the ability to set a context for a request.
func NewPutPoolsPoolIDMembersMemberIDParamsWithContext(ctx context.Context) *PutPoolsPoolIDMembersMemberIDParams {
	return &PutPoolsPoolIDMembersMemberIDParams{
		Context: ctx,
	}
}

// NewPutPoolsPoolIDMembersMemberIDParamsWithHTTPClient creates a new PutPoolsPoolIDMembersMemberIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutPoolsPoolIDMembersMemberIDParamsWithHTTPClient(client *http.Client) *PutPoolsPoolIDMembersMemberIDParams {
	return &PutPoolsPoolIDMembersMemberIDParams{
		HTTPClient: client,
	}
}

/* PutPoolsPoolIDMembersMemberIDParams contains all the parameters to send to the API endpoint
   for the put pools pool ID members member ID operation.

   Typically these are written to a http.Request.
*/
type PutPoolsPoolIDMembersMemberIDParams struct {

	// Member.
	Member PutPoolsPoolIDMembersMemberIDBody

	/* MemberID.

	   The UUID of the member

	   Format: uuid
	*/
	MemberID strfmt.UUID

	/* PoolID.

	   The UUID of the pool

	   Format: uuid
	*/
	PoolID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put pools pool ID members member ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutPoolsPoolIDMembersMemberIDParams) WithDefaults() *PutPoolsPoolIDMembersMemberIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put pools pool ID members member ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutPoolsPoolIDMembersMemberIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put pools pool ID members member ID params
func (o *PutPoolsPoolIDMembersMemberIDParams) WithTimeout(timeout time.Duration) *PutPoolsPoolIDMembersMemberIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put pools pool ID members member ID params
func (o *PutPoolsPoolIDMembersMemberIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put pools pool ID members member ID params
func (o *PutPoolsPoolIDMembersMemberIDParams) WithContext(ctx context.Context) *PutPoolsPoolIDMembersMemberIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put pools pool ID members member ID params
func (o *PutPoolsPoolIDMembersMemberIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put pools pool ID members member ID params
func (o *PutPoolsPoolIDMembersMemberIDParams) WithHTTPClient(client *http.Client) *PutPoolsPoolIDMembersMemberIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put pools pool ID members member ID params
func (o *PutPoolsPoolIDMembersMemberIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMember adds the member to the put pools pool ID members member ID params
func (o *PutPoolsPoolIDMembersMemberIDParams) WithMember(member PutPoolsPoolIDMembersMemberIDBody) *PutPoolsPoolIDMembersMemberIDParams {
	o.SetMember(member)
	return o
}

// SetMember adds the member to the put pools pool ID members member ID params
func (o *PutPoolsPoolIDMembersMemberIDParams) SetMember(member PutPoolsPoolIDMembersMemberIDBody) {
	o.Member = member
}

// WithMemberID adds the memberID to the put pools pool ID members member ID params
func (o *PutPoolsPoolIDMembersMemberIDParams) WithMemberID(memberID strfmt.UUID) *PutPoolsPoolIDMembersMemberIDParams {
	o.SetMemberID(memberID)
	return o
}

// SetMemberID adds the memberId to the put pools pool ID members member ID params
func (o *PutPoolsPoolIDMembersMemberIDParams) SetMemberID(memberID strfmt.UUID) {
	o.MemberID = memberID
}

// WithPoolID adds the poolID to the put pools pool ID members member ID params
func (o *PutPoolsPoolIDMembersMemberIDParams) WithPoolID(poolID strfmt.UUID) *PutPoolsPoolIDMembersMemberIDParams {
	o.SetPoolID(poolID)
	return o
}

// SetPoolID adds the poolId to the put pools pool ID members member ID params
func (o *PutPoolsPoolIDMembersMemberIDParams) SetPoolID(poolID strfmt.UUID) {
	o.PoolID = poolID
}

// WriteToRequest writes these params to a swagger request
func (o *PutPoolsPoolIDMembersMemberIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Member); err != nil {
		return err
	}

	// path param member_id
	if err := r.SetPathParam("member_id", o.MemberID.String()); err != nil {
		return err
	}

	// path param pool_id
	if err := r.SetPathParam("pool_id", o.PoolID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
