// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 SAP SE
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package administrative

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sapcc/andromeda/models"
)

// GetQuotasOKCode is the HTTP code returned for type GetQuotasOK
const GetQuotasOKCode int = 200

/*
GetQuotasOK A JSON array of quotas

swagger:response getQuotasOK
*/
type GetQuotasOK struct {

	/*
	  In: Body
	*/
	Payload *GetQuotasOKBody `json:"body,omitempty"`
}

// NewGetQuotasOK creates GetQuotasOK with default headers values
func NewGetQuotasOK() *GetQuotasOK {

	return &GetQuotasOK{}
}

// WithPayload adds the payload to the get quotas o k response
func (o *GetQuotasOK) WithPayload(payload *GetQuotasOKBody) *GetQuotasOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get quotas o k response
func (o *GetQuotasOK) SetPayload(payload *GetQuotasOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetQuotasOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetQuotasDefault Unexpected Error

swagger:response getQuotasDefault
*/
type GetQuotasDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetQuotasDefault creates GetQuotasDefault with default headers values
func NewGetQuotasDefault(code int) *GetQuotasDefault {
	if code <= 0 {
		code = 500
	}

	return &GetQuotasDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get quotas default response
func (o *GetQuotasDefault) WithStatusCode(code int) *GetQuotasDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get quotas default response
func (o *GetQuotasDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get quotas default response
func (o *GetQuotasDefault) WithPayload(payload *models.Error) *GetQuotasDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get quotas default response
func (o *GetQuotasDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetQuotasDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
