// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 SAP SE
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package administrative

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sapcc/andromeda/models"
)

// GetQuotasDefaultsOKCode is the HTTP code returned for type GetQuotasDefaultsOK
const GetQuotasDefaultsOKCode int = 200

/*
GetQuotasDefaultsOK Show the quota defaults configured for new projects.

swagger:response getQuotasDefaultsOK
*/
type GetQuotasDefaultsOK struct {

	/*
	  In: Body
	*/
	Payload *GetQuotasDefaultsOKBody `json:"body,omitempty"`
}

// NewGetQuotasDefaultsOK creates GetQuotasDefaultsOK with default headers values
func NewGetQuotasDefaultsOK() *GetQuotasDefaultsOK {

	return &GetQuotasDefaultsOK{}
}

// WithPayload adds the payload to the get quotas defaults o k response
func (o *GetQuotasDefaultsOK) WithPayload(payload *GetQuotasDefaultsOKBody) *GetQuotasDefaultsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get quotas defaults o k response
func (o *GetQuotasDefaultsOK) SetPayload(payload *GetQuotasDefaultsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetQuotasDefaultsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetQuotasDefaultsDefault Unexpected Error

swagger:response getQuotasDefaultsDefault
*/
type GetQuotasDefaultsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetQuotasDefaultsDefault creates GetQuotasDefaultsDefault with default headers values
func NewGetQuotasDefaultsDefault(code int) *GetQuotasDefaultsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetQuotasDefaultsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get quotas defaults default response
func (o *GetQuotasDefaultsDefault) WithStatusCode(code int) *GetQuotasDefaultsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get quotas defaults default response
func (o *GetQuotasDefaultsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get quotas defaults default response
func (o *GetQuotasDefaultsDefault) WithPayload(payload *models.Error) *GetQuotasDefaultsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get quotas defaults default response
func (o *GetQuotasDefaultsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetQuotasDefaultsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
