// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 SAP SE
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package administrative

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostSyncHandlerFunc turns a function with the right signature into a post sync handler
type PostSyncHandlerFunc func(PostSyncParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostSyncHandlerFunc) Handle(params PostSyncParams) middleware.Responder {
	return fn(params)
}

// PostSyncHandler interface for that can handle valid post sync params
type PostSyncHandler interface {
	Handle(PostSyncParams) middleware.Responder
}

// NewPostSync creates a new http.Handler for the post sync operation
func NewPostSync(ctx *middleware.Context, handler PostSyncHandler) *PostSync {
	return &PostSync{Context: ctx, Handler: handler}
}

/*
	PostSync swagger:route POST /sync Administrative postSync

Enqueue a full sync
*/
type PostSync struct {
	Context *middleware.Context
	Handler PostSyncHandler
}

func (o *PostSync) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostSyncParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
