// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 SAP SE
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package administrative

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sapcc/andromeda/models"
)

// PostSyncDomainIDAcceptedCode is the HTTP code returned for type PostSyncDomainIDAccepted
const PostSyncDomainIDAcceptedCode int = 202

/*
PostSyncDomainIDAccepted Full sync has been enqueued.

swagger:response postSyncDomainIdAccepted
*/
type PostSyncDomainIDAccepted struct {
}

// NewPostSyncDomainIDAccepted creates PostSyncDomainIDAccepted with default headers values
func NewPostSyncDomainIDAccepted() *PostSyncDomainIDAccepted {

	return &PostSyncDomainIDAccepted{}
}

// WriteResponse to the client
func (o *PostSyncDomainIDAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(202)
}

/*
PostSyncDomainIDDefault Unexpected Error

swagger:response postSyncDomainIdDefault
*/
type PostSyncDomainIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostSyncDomainIDDefault creates PostSyncDomainIDDefault with default headers values
func NewPostSyncDomainIDDefault(code int) *PostSyncDomainIDDefault {
	if code <= 0 {
		code = 500
	}

	return &PostSyncDomainIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post sync domain ID default response
func (o *PostSyncDomainIDDefault) WithStatusCode(code int) *PostSyncDomainIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post sync domain ID default response
func (o *PostSyncDomainIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post sync domain ID default response
func (o *PostSyncDomainIDDefault) WithPayload(payload *models.Error) *PostSyncDomainIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post sync domain ID default response
func (o *PostSyncDomainIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostSyncDomainIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
