// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 SAP SE
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package datacenters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/sapcc/andromeda/models"
)

// GetDatacentersDatacenterIDHandlerFunc turns a function with the right signature into a get datacenters datacenter ID handler
type GetDatacentersDatacenterIDHandlerFunc func(GetDatacentersDatacenterIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDatacentersDatacenterIDHandlerFunc) Handle(params GetDatacentersDatacenterIDParams) middleware.Responder {
	return fn(params)
}

// GetDatacentersDatacenterIDHandler interface for that can handle valid get datacenters datacenter ID params
type GetDatacentersDatacenterIDHandler interface {
	Handle(GetDatacentersDatacenterIDParams) middleware.Responder
}

// NewGetDatacentersDatacenterID creates a new http.Handler for the get datacenters datacenter ID operation
func NewGetDatacentersDatacenterID(ctx *middleware.Context, handler GetDatacentersDatacenterIDHandler) *GetDatacentersDatacenterID {
	return &GetDatacentersDatacenterID{Context: ctx, Handler: handler}
}

/*
	GetDatacentersDatacenterID swagger:route GET /datacenters/{datacenter_id} Datacenters getDatacentersDatacenterId

Show datacenter detail
*/
type GetDatacentersDatacenterID struct {
	Context *middleware.Context
	Handler GetDatacentersDatacenterIDHandler
}

func (o *GetDatacentersDatacenterID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetDatacentersDatacenterIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetDatacentersDatacenterIDOKBody get datacenters datacenter ID o k body
//
// swagger:model GetDatacentersDatacenterIDOKBody
type GetDatacentersDatacenterIDOKBody struct {

	// datacenter
	Datacenter *models.Datacenter `json:"datacenter,omitempty"`
}

// Validate validates this get datacenters datacenter ID o k body
func (o *GetDatacentersDatacenterIDOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDatacenter(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetDatacentersDatacenterIDOKBody) validateDatacenter(formats strfmt.Registry) error {
	if swag.IsZero(o.Datacenter) { // not required
		return nil
	}

	if o.Datacenter != nil {
		if err := o.Datacenter.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getDatacentersDatacenterIdOK" + "." + "datacenter")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getDatacentersDatacenterIdOK" + "." + "datacenter")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get datacenters datacenter ID o k body based on the context it is used
func (o *GetDatacentersDatacenterIDOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateDatacenter(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetDatacentersDatacenterIDOKBody) contextValidateDatacenter(ctx context.Context, formats strfmt.Registry) error {

	if o.Datacenter != nil {
		if err := o.Datacenter.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getDatacentersDatacenterIdOK" + "." + "datacenter")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getDatacentersDatacenterIdOK" + "." + "datacenter")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetDatacentersDatacenterIDOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetDatacentersDatacenterIDOKBody) UnmarshalBinary(b []byte) error {
	var res GetDatacentersDatacenterIDOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
