// Code generated by go-swagger; DO NOT EDIT.

// SPDX-FileCopyrightText: Copyright 2025 SAP SE or an SAP affiliate company
//
// SPDX-License-Identifier: Apache-2.0

package pools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeletePoolsPoolIDParams creates a new DeletePoolsPoolIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeletePoolsPoolIDParams() *DeletePoolsPoolIDParams {
	return &DeletePoolsPoolIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeletePoolsPoolIDParamsWithTimeout creates a new DeletePoolsPoolIDParams object
// with the ability to set a timeout on a request.
func NewDeletePoolsPoolIDParamsWithTimeout(timeout time.Duration) *DeletePoolsPoolIDParams {
	return &DeletePoolsPoolIDParams{
		timeout: timeout,
	}
}

// NewDeletePoolsPoolIDParamsWithContext creates a new DeletePoolsPoolIDParams object
// with the ability to set a context for a request.
func NewDeletePoolsPoolIDParamsWithContext(ctx context.Context) *DeletePoolsPoolIDParams {
	return &DeletePoolsPoolIDParams{
		Context: ctx,
	}
}

// NewDeletePoolsPoolIDParamsWithHTTPClient creates a new DeletePoolsPoolIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeletePoolsPoolIDParamsWithHTTPClient(client *http.Client) *DeletePoolsPoolIDParams {
	return &DeletePoolsPoolIDParams{
		HTTPClient: client,
	}
}

/*
DeletePoolsPoolIDParams contains all the parameters to send to the API endpoint

	for the delete pools pool ID operation.

	Typically these are written to a http.Request.
*/
type DeletePoolsPoolIDParams struct {

	/* PoolID.

	   The UUID of the pool

	   Format: uuid
	*/
	PoolID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete pools pool ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeletePoolsPoolIDParams) WithDefaults() *DeletePoolsPoolIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete pools pool ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeletePoolsPoolIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete pools pool ID params
func (o *DeletePoolsPoolIDParams) WithTimeout(timeout time.Duration) *DeletePoolsPoolIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete pools pool ID params
func (o *DeletePoolsPoolIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete pools pool ID params
func (o *DeletePoolsPoolIDParams) WithContext(ctx context.Context) *DeletePoolsPoolIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete pools pool ID params
func (o *DeletePoolsPoolIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete pools pool ID params
func (o *DeletePoolsPoolIDParams) WithHTTPClient(client *http.Client) *DeletePoolsPoolIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete pools pool ID params
func (o *DeletePoolsPoolIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPoolID adds the poolID to the delete pools pool ID params
func (o *DeletePoolsPoolIDParams) WithPoolID(poolID strfmt.UUID) *DeletePoolsPoolIDParams {
	o.SetPoolID(poolID)
	return o
}

// SetPoolID adds the poolId to the delete pools pool ID params
func (o *DeletePoolsPoolIDParams) SetPoolID(poolID strfmt.UUID) {
	o.PoolID = poolID
}

// WriteToRequest writes these params to a swagger request
func (o *DeletePoolsPoolIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param pool_id
	if err := r.SetPathParam("pool_id", o.PoolID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
