// Code generated by go-swagger; DO NOT EDIT.

// SPDX-FileCopyrightText: Copyright 2025 SAP SE or an SAP affiliate company
//
// SPDX-License-Identifier: Apache-2.0

package metrics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/sapcc/andromeda/models"
)

// GetMetricsAkamaiTotalDNSRequestsReader is a Reader for the GetMetricsAkamaiTotalDNSRequests structure.
type GetMetricsAkamaiTotalDNSRequestsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMetricsAkamaiTotalDNSRequestsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetMetricsAkamaiTotalDNSRequestsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetMetricsAkamaiTotalDNSRequestsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetMetricsAkamaiTotalDNSRequestsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetMetricsAkamaiTotalDNSRequestsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetMetricsAkamaiTotalDNSRequestsOK creates a GetMetricsAkamaiTotalDNSRequestsOK with default headers values
func NewGetMetricsAkamaiTotalDNSRequestsOK() *GetMetricsAkamaiTotalDNSRequestsOK {
	return &GetMetricsAkamaiTotalDNSRequestsOK{}
}

/*
GetMetricsAkamaiTotalDNSRequestsOK describes a response with status code 200, with default header values.

A JSON object containing DNS request metrics
*/
type GetMetricsAkamaiTotalDNSRequestsOK struct {
	Payload *GetMetricsAkamaiTotalDNSRequestsOKBody
}

// IsSuccess returns true when this get metrics akamai total Dns requests o k response has a 2xx status code
func (o *GetMetricsAkamaiTotalDNSRequestsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get metrics akamai total Dns requests o k response has a 3xx status code
func (o *GetMetricsAkamaiTotalDNSRequestsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get metrics akamai total Dns requests o k response has a 4xx status code
func (o *GetMetricsAkamaiTotalDNSRequestsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get metrics akamai total Dns requests o k response has a 5xx status code
func (o *GetMetricsAkamaiTotalDNSRequestsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get metrics akamai total Dns requests o k response a status code equal to that given
func (o *GetMetricsAkamaiTotalDNSRequestsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get metrics akamai total Dns requests o k response
func (o *GetMetricsAkamaiTotalDNSRequestsOK) Code() int {
	return 200
}

func (o *GetMetricsAkamaiTotalDNSRequestsOK) Error() string {
	return fmt.Sprintf("[GET /metrics/akamai/total-dns-requests][%d] getMetricsAkamaiTotalDnsRequestsOK  %+v", 200, o.Payload)
}

func (o *GetMetricsAkamaiTotalDNSRequestsOK) String() string {
	return fmt.Sprintf("[GET /metrics/akamai/total-dns-requests][%d] getMetricsAkamaiTotalDnsRequestsOK  %+v", 200, o.Payload)
}

func (o *GetMetricsAkamaiTotalDNSRequestsOK) GetPayload() *GetMetricsAkamaiTotalDNSRequestsOKBody {
	return o.Payload
}

func (o *GetMetricsAkamaiTotalDNSRequestsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetMetricsAkamaiTotalDNSRequestsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMetricsAkamaiTotalDNSRequestsBadRequest creates a GetMetricsAkamaiTotalDNSRequestsBadRequest with default headers values
func NewGetMetricsAkamaiTotalDNSRequestsBadRequest() *GetMetricsAkamaiTotalDNSRequestsBadRequest {
	return &GetMetricsAkamaiTotalDNSRequestsBadRequest{}
}

/*
GetMetricsAkamaiTotalDNSRequestsBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetMetricsAkamaiTotalDNSRequestsBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this get metrics akamai total Dns requests bad request response has a 2xx status code
func (o *GetMetricsAkamaiTotalDNSRequestsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get metrics akamai total Dns requests bad request response has a 3xx status code
func (o *GetMetricsAkamaiTotalDNSRequestsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get metrics akamai total Dns requests bad request response has a 4xx status code
func (o *GetMetricsAkamaiTotalDNSRequestsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get metrics akamai total Dns requests bad request response has a 5xx status code
func (o *GetMetricsAkamaiTotalDNSRequestsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get metrics akamai total Dns requests bad request response a status code equal to that given
func (o *GetMetricsAkamaiTotalDNSRequestsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get metrics akamai total Dns requests bad request response
func (o *GetMetricsAkamaiTotalDNSRequestsBadRequest) Code() int {
	return 400
}

func (o *GetMetricsAkamaiTotalDNSRequestsBadRequest) Error() string {
	return fmt.Sprintf("[GET /metrics/akamai/total-dns-requests][%d] getMetricsAkamaiTotalDnsRequestsBadRequest  %+v", 400, o.Payload)
}

func (o *GetMetricsAkamaiTotalDNSRequestsBadRequest) String() string {
	return fmt.Sprintf("[GET /metrics/akamai/total-dns-requests][%d] getMetricsAkamaiTotalDnsRequestsBadRequest  %+v", 400, o.Payload)
}

func (o *GetMetricsAkamaiTotalDNSRequestsBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetMetricsAkamaiTotalDNSRequestsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMetricsAkamaiTotalDNSRequestsNotFound creates a GetMetricsAkamaiTotalDNSRequestsNotFound with default headers values
func NewGetMetricsAkamaiTotalDNSRequestsNotFound() *GetMetricsAkamaiTotalDNSRequestsNotFound {
	return &GetMetricsAkamaiTotalDNSRequestsNotFound{}
}

/*
GetMetricsAkamaiTotalDNSRequestsNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetMetricsAkamaiTotalDNSRequestsNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this get metrics akamai total Dns requests not found response has a 2xx status code
func (o *GetMetricsAkamaiTotalDNSRequestsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get metrics akamai total Dns requests not found response has a 3xx status code
func (o *GetMetricsAkamaiTotalDNSRequestsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get metrics akamai total Dns requests not found response has a 4xx status code
func (o *GetMetricsAkamaiTotalDNSRequestsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get metrics akamai total Dns requests not found response has a 5xx status code
func (o *GetMetricsAkamaiTotalDNSRequestsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get metrics akamai total Dns requests not found response a status code equal to that given
func (o *GetMetricsAkamaiTotalDNSRequestsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get metrics akamai total Dns requests not found response
func (o *GetMetricsAkamaiTotalDNSRequestsNotFound) Code() int {
	return 404
}

func (o *GetMetricsAkamaiTotalDNSRequestsNotFound) Error() string {
	return fmt.Sprintf("[GET /metrics/akamai/total-dns-requests][%d] getMetricsAkamaiTotalDnsRequestsNotFound  %+v", 404, o.Payload)
}

func (o *GetMetricsAkamaiTotalDNSRequestsNotFound) String() string {
	return fmt.Sprintf("[GET /metrics/akamai/total-dns-requests][%d] getMetricsAkamaiTotalDnsRequestsNotFound  %+v", 404, o.Payload)
}

func (o *GetMetricsAkamaiTotalDNSRequestsNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetMetricsAkamaiTotalDNSRequestsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMetricsAkamaiTotalDNSRequestsDefault creates a GetMetricsAkamaiTotalDNSRequestsDefault with default headers values
func NewGetMetricsAkamaiTotalDNSRequestsDefault(code int) *GetMetricsAkamaiTotalDNSRequestsDefault {
	return &GetMetricsAkamaiTotalDNSRequestsDefault{
		_statusCode: code,
	}
}

/*
GetMetricsAkamaiTotalDNSRequestsDefault describes a response with status code -1, with default header values.

Unexpected Error
*/
type GetMetricsAkamaiTotalDNSRequestsDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this get metrics akamai total DNS requests default response has a 2xx status code
func (o *GetMetricsAkamaiTotalDNSRequestsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get metrics akamai total DNS requests default response has a 3xx status code
func (o *GetMetricsAkamaiTotalDNSRequestsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get metrics akamai total DNS requests default response has a 4xx status code
func (o *GetMetricsAkamaiTotalDNSRequestsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get metrics akamai total DNS requests default response has a 5xx status code
func (o *GetMetricsAkamaiTotalDNSRequestsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get metrics akamai total DNS requests default response a status code equal to that given
func (o *GetMetricsAkamaiTotalDNSRequestsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get metrics akamai total DNS requests default response
func (o *GetMetricsAkamaiTotalDNSRequestsDefault) Code() int {
	return o._statusCode
}

func (o *GetMetricsAkamaiTotalDNSRequestsDefault) Error() string {
	return fmt.Sprintf("[GET /metrics/akamai/total-dns-requests][%d] GetMetricsAkamaiTotalDNSRequests default  %+v", o._statusCode, o.Payload)
}

func (o *GetMetricsAkamaiTotalDNSRequestsDefault) String() string {
	return fmt.Sprintf("[GET /metrics/akamai/total-dns-requests][%d] GetMetricsAkamaiTotalDNSRequests default  %+v", o._statusCode, o.Payload)
}

func (o *GetMetricsAkamaiTotalDNSRequestsDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetMetricsAkamaiTotalDNSRequestsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetMetricsAkamaiTotalDNSRequestsOKBody get metrics akamai total DNS requests o k body
swagger:model GetMetricsAkamaiTotalDNSRequestsOKBody
*/
type GetMetricsAkamaiTotalDNSRequestsOKBody struct {

	// total dns requests
	TotalDNSRequests *models.AkamaiTotalDNSRequests `json:"total_dns_requests,omitempty"`
}

// Validate validates this get metrics akamai total DNS requests o k body
func (o *GetMetricsAkamaiTotalDNSRequestsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateTotalDNSRequests(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetMetricsAkamaiTotalDNSRequestsOKBody) validateTotalDNSRequests(formats strfmt.Registry) error {
	if swag.IsZero(o.TotalDNSRequests) { // not required
		return nil
	}

	if o.TotalDNSRequests != nil {
		if err := o.TotalDNSRequests.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getMetricsAkamaiTotalDnsRequestsOK" + "." + "total_dns_requests")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getMetricsAkamaiTotalDnsRequestsOK" + "." + "total_dns_requests")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get metrics akamai total DNS requests o k body based on the context it is used
func (o *GetMetricsAkamaiTotalDNSRequestsOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateTotalDNSRequests(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetMetricsAkamaiTotalDNSRequestsOKBody) contextValidateTotalDNSRequests(ctx context.Context, formats strfmt.Registry) error {

	if o.TotalDNSRequests != nil {
		if err := o.TotalDNSRequests.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getMetricsAkamaiTotalDnsRequestsOK" + "." + "total_dns_requests")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getMetricsAkamaiTotalDnsRequestsOK" + "." + "total_dns_requests")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetMetricsAkamaiTotalDNSRequestsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetMetricsAkamaiTotalDNSRequestsOKBody) UnmarshalBinary(b []byte) error {
	var res GetMetricsAkamaiTotalDNSRequestsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
