DEFAULT:
  host: 127.0.0.1
  transport_url: nats://localhost:4222
  prometheus: true
  prometheus_listen: 0.0.0.0:9092
  debug: true

api_settings:
  auth_strategy: noop  # Using noop for local development
  policy_engine: noop  # Simplified for local testing
  pagination_max_limit: 100
  rate_limit: 10
  disable_pagination: false
  disable_sorting: false
  disable_cors: false

database:
  connection: mariadb://andromeda:andromeda@localhost/andromeda_db

audit_middleware_notifications:
  enabled: false

house_keeping:
  enabled: false

quota:
  enabled: false