// Code generated by go-swagger; DO NOT EDIT.

// SPDX-FileCopyrightText: Copyright 2025 SAP SE or an SAP affiliate company
//
// SPDX-License-Identifier: Apache-2.0

package pools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sapcc/andromeda/models"
)

// PostPoolsCreatedCode is the HTTP code returned for type PostPoolsCreated
const PostPoolsCreatedCode int = 201

/*
PostPoolsCreated Created pool.

swagger:response postPoolsCreated
*/
type PostPoolsCreated struct {

	/*
	  In: Body
	*/
	Payload *PostPoolsCreatedBody `json:"body,omitempty"`
}

// NewPostPoolsCreated creates PostPoolsCreated with default headers values
func NewPostPoolsCreated() *PostPoolsCreated {

	return &PostPoolsCreated{}
}

// WithPayload adds the payload to the post pools created response
func (o *PostPoolsCreated) WithPayload(payload *PostPoolsCreatedBody) *PostPoolsCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post pools created response
func (o *PostPoolsCreated) SetPayload(payload *PostPoolsCreatedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostPoolsCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostPoolsBadRequestCode is the HTTP code returned for type PostPoolsBadRequest
const PostPoolsBadRequestCode int = 400

/*
PostPoolsBadRequest Bad request

swagger:response postPoolsBadRequest
*/
type PostPoolsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostPoolsBadRequest creates PostPoolsBadRequest with default headers values
func NewPostPoolsBadRequest() *PostPoolsBadRequest {

	return &PostPoolsBadRequest{}
}

// WithPayload adds the payload to the post pools bad request response
func (o *PostPoolsBadRequest) WithPayload(payload *models.Error) *PostPoolsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post pools bad request response
func (o *PostPoolsBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostPoolsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
PostPoolsDefault Unexpected Error

swagger:response postPoolsDefault
*/
type PostPoolsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostPoolsDefault creates PostPoolsDefault with default headers values
func NewPostPoolsDefault(code int) *PostPoolsDefault {
	if code <= 0 {
		code = 500
	}

	return &PostPoolsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post pools default response
func (o *PostPoolsDefault) WithStatusCode(code int) *PostPoolsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post pools default response
func (o *PostPoolsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post pools default response
func (o *PostPoolsDefault) WithPayload(payload *models.Error) *PostPoolsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post pools default response
func (o *PostPoolsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostPoolsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
