// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 SAP SE
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package geographic_maps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sapcc/andromeda/models"
)

// GetGeomapsOKCode is the HTTP code returned for type GetGeomapsOK
const GetGeomapsOKCode int = 200

/*
GetGeomapsOK A JSON array of geographic maps

swagger:response getGeomapsOK
*/
type GetGeomapsOK struct {

	/*
	  In: Body
	*/
	Payload *GetGeomapsOKBody `json:"body,omitempty"`
}

// NewGetGeomapsOK creates GetGeomapsOK with default headers values
func NewGetGeomapsOK() *GetGeomapsOK {

	return &GetGeomapsOK{}
}

// WithPayload adds the payload to the get geomaps o k response
func (o *GetGeomapsOK) WithPayload(payload *GetGeomapsOKBody) *GetGeomapsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get geomaps o k response
func (o *GetGeomapsOK) SetPayload(payload *GetGeomapsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGeomapsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetGeomapsBadRequestCode is the HTTP code returned for type GetGeomapsBadRequest
const GetGeomapsBadRequestCode int = 400

/*
GetGeomapsBadRequest Bad request

swagger:response getGeomapsBadRequest
*/
type GetGeomapsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetGeomapsBadRequest creates GetGeomapsBadRequest with default headers values
func NewGetGeomapsBadRequest() *GetGeomapsBadRequest {

	return &GetGeomapsBadRequest{}
}

// WithPayload adds the payload to the get geomaps bad request response
func (o *GetGeomapsBadRequest) WithPayload(payload *models.Error) *GetGeomapsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get geomaps bad request response
func (o *GetGeomapsBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGeomapsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetGeomapsDefault Unexpected Error

swagger:response getGeomapsDefault
*/
type GetGeomapsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetGeomapsDefault creates GetGeomapsDefault with default headers values
func NewGetGeomapsDefault(code int) *GetGeomapsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetGeomapsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get geomaps default response
func (o *GetGeomapsDefault) WithStatusCode(code int) *GetGeomapsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get geomaps default response
func (o *GetGeomapsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get geomaps default response
func (o *GetGeomapsDefault) WithPayload(payload *models.Error) *GetGeomapsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get geomaps default response
func (o *GetGeomapsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGeomapsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
