// Code generated by go-swagger; DO NOT EDIT.

// SPDX-FileCopyrightText: Copyright 2025 SAP SE or an SAP affiliate company
//
// SPDX-License-Identifier: Apache-2.0

package geographic_maps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/sapcc/andromeda/models"
)

// GetGeomapsGeomapIDHandlerFunc turns a function with the right signature into a get geomaps geomap ID handler
type GetGeomapsGeomapIDHandlerFunc func(GetGeomapsGeomapIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetGeomapsGeomapIDHandlerFunc) Handle(params GetGeomapsGeomapIDParams) middleware.Responder {
	return fn(params)
}

// GetGeomapsGeomapIDHandler interface for that can handle valid get geomaps geomap ID params
type GetGeomapsGeomapIDHandler interface {
	Handle(GetGeomapsGeomapIDParams) middleware.Responder
}

// NewGetGeomapsGeomapID creates a new http.Handler for the get geomaps geomap ID operation
func NewGetGeomapsGeomapID(ctx *middleware.Context, handler GetGeomapsGeomapIDHandler) *GetGeomapsGeomapID {
	return &GetGeomapsGeomapID{Context: ctx, Handler: handler}
}

/*
	GetGeomapsGeomapID swagger:route GET /geomaps/{geomap_id} Geographic maps getGeomapsGeomapId

Show geographic map detail
*/
type GetGeomapsGeomapID struct {
	Context *middleware.Context
	Handler GetGeomapsGeomapIDHandler
}

func (o *GetGeomapsGeomapID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetGeomapsGeomapIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetGeomapsGeomapIDOKBody get geomaps geomap ID o k body
//
// swagger:model GetGeomapsGeomapIDOKBody
type GetGeomapsGeomapIDOKBody struct {

	// geomap
	Geomap *models.Geomap `json:"geomap,omitempty"`
}

// Validate validates this get geomaps geomap ID o k body
func (o *GetGeomapsGeomapIDOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateGeomap(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetGeomapsGeomapIDOKBody) validateGeomap(formats strfmt.Registry) error {
	if swag.IsZero(o.Geomap) { // not required
		return nil
	}

	if o.Geomap != nil {
		if err := o.Geomap.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getGeomapsGeomapIdOK" + "." + "geomap")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getGeomapsGeomapIdOK" + "." + "geomap")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get geomaps geomap ID o k body based on the context it is used
func (o *GetGeomapsGeomapIDOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateGeomap(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetGeomapsGeomapIDOKBody) contextValidateGeomap(ctx context.Context, formats strfmt.Registry) error {

	if o.Geomap != nil {
		if err := o.Geomap.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getGeomapsGeomapIdOK" + "." + "geomap")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getGeomapsGeomapIdOK" + "." + "geomap")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetGeomapsGeomapIDOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetGeomapsGeomapIDOKBody) UnmarshalBinary(b []byte) error {
	var res GetGeomapsGeomapIDOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
