// Code generated by go-swagger; DO NOT EDIT.

// SPDX-FileCopyrightText: Copyright 2025 SAP SE or an SAP affiliate company
//
// SPDX-License-Identifier: Apache-2.0

package monitors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteMonitorsMonitorIDHandlerFunc turns a function with the right signature into a delete monitors monitor ID handler
type DeleteMonitorsMonitorIDHandlerFunc func(DeleteMonitorsMonitorIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteMonitorsMonitorIDHandlerFunc) Handle(params DeleteMonitorsMonitorIDParams) middleware.Responder {
	return fn(params)
}

// DeleteMonitorsMonitorIDHandler interface for that can handle valid delete monitors monitor ID params
type DeleteMonitorsMonitorIDHandler interface {
	Handle(DeleteMonitorsMonitorIDParams) middleware.Responder
}

// NewDeleteMonitorsMonitorID creates a new http.Handler for the delete monitors monitor ID operation
func NewDeleteMonitorsMonitorID(ctx *middleware.Context, handler DeleteMonitorsMonitorIDHandler) *DeleteMonitorsMonitorID {
	return &DeleteMonitorsMonitorID{Context: ctx, Handler: handler}
}

/*
	DeleteMonitorsMonitorID swagger:route DELETE /monitors/{monitor_id} Monitors deleteMonitorsMonitorId

Delete a monitor
*/
type DeleteMonitorsMonitorID struct {
	Context *middleware.Context
	Handler DeleteMonitorsMonitorIDHandler
}

func (o *DeleteMonitorsMonitorID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteMonitorsMonitorIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
