// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 SAP SE
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package monitors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/sapcc/andromeda/models"
)

// GetMonitorsMonitorIDHandlerFunc turns a function with the right signature into a get monitors monitor ID handler
type GetMonitorsMonitorIDHandlerFunc func(GetMonitorsMonitorIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetMonitorsMonitorIDHandlerFunc) Handle(params GetMonitorsMonitorIDParams) middleware.Responder {
	return fn(params)
}

// GetMonitorsMonitorIDHandler interface for that can handle valid get monitors monitor ID params
type GetMonitorsMonitorIDHandler interface {
	Handle(GetMonitorsMonitorIDParams) middleware.Responder
}

// NewGetMonitorsMonitorID creates a new http.Handler for the get monitors monitor ID operation
func NewGetMonitorsMonitorID(ctx *middleware.Context, handler GetMonitorsMonitorIDHandler) *GetMonitorsMonitorID {
	return &GetMonitorsMonitorID{Context: ctx, Handler: handler}
}

/*
	GetMonitorsMonitorID swagger:route GET /monitors/{monitor_id} Monitors getMonitorsMonitorId

Show monitor detail
*/
type GetMonitorsMonitorID struct {
	Context *middleware.Context
	Handler GetMonitorsMonitorIDHandler
}

func (o *GetMonitorsMonitorID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetMonitorsMonitorIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetMonitorsMonitorIDOKBody get monitors monitor ID o k body
//
// swagger:model GetMonitorsMonitorIDOKBody
type GetMonitorsMonitorIDOKBody struct {

	// monitor
	Monitor *models.Monitor `json:"monitor,omitempty"`
}

// Validate validates this get monitors monitor ID o k body
func (o *GetMonitorsMonitorIDOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMonitor(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetMonitorsMonitorIDOKBody) validateMonitor(formats strfmt.Registry) error {
	if swag.IsZero(o.Monitor) { // not required
		return nil
	}

	if o.Monitor != nil {
		if err := o.Monitor.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getMonitorsMonitorIdOK" + "." + "monitor")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getMonitorsMonitorIdOK" + "." + "monitor")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get monitors monitor ID o k body based on the context it is used
func (o *GetMonitorsMonitorIDOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateMonitor(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetMonitorsMonitorIDOKBody) contextValidateMonitor(ctx context.Context, formats strfmt.Registry) error {

	if o.Monitor != nil {
		if err := o.Monitor.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getMonitorsMonitorIdOK" + "." + "monitor")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getMonitorsMonitorIdOK" + "." + "monitor")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetMonitorsMonitorIDOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetMonitorsMonitorIDOKBody) UnmarshalBinary(b []byte) error {
	var res GetMonitorsMonitorIDOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
