// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 SAP SE
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package datacenters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/sapcc/andromeda/models"
)

// GetDatacentersDatacenterIDReader is a Reader for the GetDatacentersDatacenterID structure.
type GetDatacentersDatacenterIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDatacentersDatacenterIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDatacentersDatacenterIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetDatacentersDatacenterIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetDatacentersDatacenterIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetDatacentersDatacenterIDOK creates a GetDatacentersDatacenterIDOK with default headers values
func NewGetDatacentersDatacenterIDOK() *GetDatacentersDatacenterIDOK {
	return &GetDatacentersDatacenterIDOK{}
}

/*
GetDatacentersDatacenterIDOK describes a response with status code 200, with default header values.

Shows the details of a specific datacenter.
*/
type GetDatacentersDatacenterIDOK struct {
	Payload *GetDatacentersDatacenterIDOKBody
}

// IsSuccess returns true when this get datacenters datacenter Id o k response has a 2xx status code
func (o *GetDatacentersDatacenterIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get datacenters datacenter Id o k response has a 3xx status code
func (o *GetDatacentersDatacenterIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get datacenters datacenter Id o k response has a 4xx status code
func (o *GetDatacentersDatacenterIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get datacenters datacenter Id o k response has a 5xx status code
func (o *GetDatacentersDatacenterIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get datacenters datacenter Id o k response a status code equal to that given
func (o *GetDatacentersDatacenterIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get datacenters datacenter Id o k response
func (o *GetDatacentersDatacenterIDOK) Code() int {
	return 200
}

func (o *GetDatacentersDatacenterIDOK) Error() string {
	return fmt.Sprintf("[GET /datacenters/{datacenter_id}][%d] getDatacentersDatacenterIdOK  %+v", 200, o.Payload)
}

func (o *GetDatacentersDatacenterIDOK) String() string {
	return fmt.Sprintf("[GET /datacenters/{datacenter_id}][%d] getDatacentersDatacenterIdOK  %+v", 200, o.Payload)
}

func (o *GetDatacentersDatacenterIDOK) GetPayload() *GetDatacentersDatacenterIDOKBody {
	return o.Payload
}

func (o *GetDatacentersDatacenterIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetDatacentersDatacenterIDOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDatacentersDatacenterIDNotFound creates a GetDatacentersDatacenterIDNotFound with default headers values
func NewGetDatacentersDatacenterIDNotFound() *GetDatacentersDatacenterIDNotFound {
	return &GetDatacentersDatacenterIDNotFound{}
}

/*
GetDatacentersDatacenterIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetDatacentersDatacenterIDNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this get datacenters datacenter Id not found response has a 2xx status code
func (o *GetDatacentersDatacenterIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get datacenters datacenter Id not found response has a 3xx status code
func (o *GetDatacentersDatacenterIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get datacenters datacenter Id not found response has a 4xx status code
func (o *GetDatacentersDatacenterIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get datacenters datacenter Id not found response has a 5xx status code
func (o *GetDatacentersDatacenterIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get datacenters datacenter Id not found response a status code equal to that given
func (o *GetDatacentersDatacenterIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get datacenters datacenter Id not found response
func (o *GetDatacentersDatacenterIDNotFound) Code() int {
	return 404
}

func (o *GetDatacentersDatacenterIDNotFound) Error() string {
	return fmt.Sprintf("[GET /datacenters/{datacenter_id}][%d] getDatacentersDatacenterIdNotFound  %+v", 404, o.Payload)
}

func (o *GetDatacentersDatacenterIDNotFound) String() string {
	return fmt.Sprintf("[GET /datacenters/{datacenter_id}][%d] getDatacentersDatacenterIdNotFound  %+v", 404, o.Payload)
}

func (o *GetDatacentersDatacenterIDNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetDatacentersDatacenterIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDatacentersDatacenterIDDefault creates a GetDatacentersDatacenterIDDefault with default headers values
func NewGetDatacentersDatacenterIDDefault(code int) *GetDatacentersDatacenterIDDefault {
	return &GetDatacentersDatacenterIDDefault{
		_statusCode: code,
	}
}

/*
GetDatacentersDatacenterIDDefault describes a response with status code -1, with default header values.

Unexpected Error
*/
type GetDatacentersDatacenterIDDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this get datacenters datacenter ID default response has a 2xx status code
func (o *GetDatacentersDatacenterIDDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get datacenters datacenter ID default response has a 3xx status code
func (o *GetDatacentersDatacenterIDDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get datacenters datacenter ID default response has a 4xx status code
func (o *GetDatacentersDatacenterIDDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get datacenters datacenter ID default response has a 5xx status code
func (o *GetDatacentersDatacenterIDDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get datacenters datacenter ID default response a status code equal to that given
func (o *GetDatacentersDatacenterIDDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get datacenters datacenter ID default response
func (o *GetDatacentersDatacenterIDDefault) Code() int {
	return o._statusCode
}

func (o *GetDatacentersDatacenterIDDefault) Error() string {
	return fmt.Sprintf("[GET /datacenters/{datacenter_id}][%d] GetDatacentersDatacenterID default  %+v", o._statusCode, o.Payload)
}

func (o *GetDatacentersDatacenterIDDefault) String() string {
	return fmt.Sprintf("[GET /datacenters/{datacenter_id}][%d] GetDatacentersDatacenterID default  %+v", o._statusCode, o.Payload)
}

func (o *GetDatacentersDatacenterIDDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetDatacentersDatacenterIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetDatacentersDatacenterIDOKBody get datacenters datacenter ID o k body
swagger:model GetDatacentersDatacenterIDOKBody
*/
type GetDatacentersDatacenterIDOKBody struct {

	// datacenter
	Datacenter *models.Datacenter `json:"datacenter,omitempty"`
}

// Validate validates this get datacenters datacenter ID o k body
func (o *GetDatacentersDatacenterIDOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDatacenter(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetDatacentersDatacenterIDOKBody) validateDatacenter(formats strfmt.Registry) error {
	if swag.IsZero(o.Datacenter) { // not required
		return nil
	}

	if o.Datacenter != nil {
		if err := o.Datacenter.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getDatacentersDatacenterIdOK" + "." + "datacenter")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getDatacentersDatacenterIdOK" + "." + "datacenter")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this get datacenters datacenter ID o k body based on the context it is used
func (o *GetDatacentersDatacenterIDOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateDatacenter(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetDatacentersDatacenterIDOKBody) contextValidateDatacenter(ctx context.Context, formats strfmt.Registry) error {

	if o.Datacenter != nil {
		if err := o.Datacenter.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("getDatacentersDatacenterIdOK" + "." + "datacenter")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("getDatacentersDatacenterIdOK" + "." + "datacenter")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetDatacentersDatacenterIDOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetDatacentersDatacenterIDOKBody) UnmarshalBinary(b []byte) error {
	var res GetDatacentersDatacenterIDOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
