// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 SAP SE
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package members

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/sapcc/andromeda/models"
)

// DeletePoolsPoolIDMembersMemberIDNoContentCode is the HTTP code returned for type DeletePoolsPoolIDMembersMemberIDNoContent
const DeletePoolsPoolIDMembersMemberIDNoContentCode int = 204

/*
DeletePoolsPoolIDMembersMemberIDNoContent Resource successfully deleted.

swagger:response deletePoolsPoolIdMembersMemberIdNoContent
*/
type DeletePoolsPoolIDMembersMemberIDNoContent struct {
}

// NewDeletePoolsPoolIDMembersMemberIDNoContent creates DeletePoolsPoolIDMembersMemberIDNoContent with default headers values
func NewDeletePoolsPoolIDMembersMemberIDNoContent() *DeletePoolsPoolIDMembersMemberIDNoContent {

	return &DeletePoolsPoolIDMembersMemberIDNoContent{}
}

// WriteResponse to the client
func (o *DeletePoolsPoolIDMembersMemberIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeletePoolsPoolIDMembersMemberIDNotFoundCode is the HTTP code returned for type DeletePoolsPoolIDMembersMemberIDNotFound
const DeletePoolsPoolIDMembersMemberIDNotFoundCode int = 404

/*
DeletePoolsPoolIDMembersMemberIDNotFound Not Found

swagger:response deletePoolsPoolIdMembersMemberIdNotFound
*/
type DeletePoolsPoolIDMembersMemberIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeletePoolsPoolIDMembersMemberIDNotFound creates DeletePoolsPoolIDMembersMemberIDNotFound with default headers values
func NewDeletePoolsPoolIDMembersMemberIDNotFound() *DeletePoolsPoolIDMembersMemberIDNotFound {

	return &DeletePoolsPoolIDMembersMemberIDNotFound{}
}

// WithPayload adds the payload to the delete pools pool Id members member Id not found response
func (o *DeletePoolsPoolIDMembersMemberIDNotFound) WithPayload(payload *models.Error) *DeletePoolsPoolIDMembersMemberIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete pools pool Id members member Id not found response
func (o *DeletePoolsPoolIDMembersMemberIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletePoolsPoolIDMembersMemberIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
DeletePoolsPoolIDMembersMemberIDDefault Unexpected Error

swagger:response deletePoolsPoolIdMembersMemberIdDefault
*/
type DeletePoolsPoolIDMembersMemberIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeletePoolsPoolIDMembersMemberIDDefault creates DeletePoolsPoolIDMembersMemberIDDefault with default headers values
func NewDeletePoolsPoolIDMembersMemberIDDefault(code int) *DeletePoolsPoolIDMembersMemberIDDefault {
	if code <= 0 {
		code = 500
	}

	return &DeletePoolsPoolIDMembersMemberIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete pools pool ID members member ID default response
func (o *DeletePoolsPoolIDMembersMemberIDDefault) WithStatusCode(code int) *DeletePoolsPoolIDMembersMemberIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete pools pool ID members member ID default response
func (o *DeletePoolsPoolIDMembersMemberIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete pools pool ID members member ID default response
func (o *DeletePoolsPoolIDMembersMemberIDDefault) WithPayload(payload *models.Error) *DeletePoolsPoolIDMembersMemberIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete pools pool ID members member ID default response
func (o *DeletePoolsPoolIDMembersMemberIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletePoolsPoolIDMembersMemberIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
